# Generated by Django 4.2.4 on 2024-07-29 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('box', models.CharField(choices=[('AV', 'Avtomat'), ('MEX', 'Mexanika')], default='MEX', max_length=3)),
            ],
        ),
    ]
