# Generated by Django 4.2.4 on 2024-08-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_car_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='box_fuel',
            field=models.CharField(choices=[('GA', 'Gaz'), ('BEN', 'Benzin'), ('To', 'Toq')], default='GA', max_length=100),
        ),
    ]
