# Generated by Django 4.2.4 on 2024-08-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_car_box_fuel'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='four_people',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
