# Generated by Django 4.2.4 on 2024-08-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_car_four_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='box',
            field=models.CharField(choices=[('Avtomat', 'Avtomat'), ('Mexanika', 'Mexanika')], default='Mexanika', max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='box_fuel',
            field=models.CharField(choices=[('Gaz', 'Gaz'), ('Benzin', 'Benzin'), ('Toq', 'Toq')], default='Gaz', max_length=100),
        ),
    ]
